### ISSUE TITLE
Re run CI

### ISSUE THREAD

**Issue by hadim** [conda-forge/argo-workflows-dsl-feedstock#1]
This repo depends on https://github.com/conda-forge/argo-workflows-feedstock that wasn't available at the time CI of this repo started.

https://github.com/conda-forge/argo-workflows-feedstock is now available.

So the CI on `master` must be run again.

ping @scopatz

**Comment by hadim** [comment]
@conda-forge/help-python

**Comment by beckermr** [comment]
you are a maintainer here so the easiest thing to do is to make an empty commit to master
